### ISSUE TITLE
find relationship between files and different workflows

### ISSUE THREAD

**Issue by clundin55** [aniehuser/senior-design-group10#139] opened 2019-04-04 01:29 UTC

**Comment by aniehuser** [comment] 2019-04-08 03:39
If this is to be done on the run page I'll do this.

**Comment by clundin55** [comment] 2019-04-08 20:45
@aniehuser yes bower's wanted this

**Comment by aniehuser** [comment] 2019-04-17 21:32
duplicate of https://github.com/aniehuser/senior-design-group10/issues/159 closing

**Closed as completed by aniehuser** 2019-04-17 21:32 UTC
